name: eduguide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.10.0
  cloud_firestore: ^6.0.0
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  firebase_storage: ^13.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # This line adds the dependency for the icon generator
  flutter_launcher_icons: ^0.13.1

# Configuration for the icon generator
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
